---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
 
  - name: Who Am I?
    shell: /bin/whoami

  - name: CPU Info
    shell: cat /proc/cpuinfo
